### ISSUE TITLE
Wondering any build example for ios application ? 

### ISSUE THREAD

**Issue by yikaus** [JensRavens/docker-swift#1]
Great example to use docker swift build

However , go through the apple 's repo , the package example are simple pure swift source , is any xcode project example around ? want to find out how can build a xcode project . Or if it is possible ? 

Thanks 
Kevin

**Comment by JensRavens** [comment]
Linux does not support Xcode, including the iOS SDK. Therefore you won't be able to build iOS apps on linux. Swift on linux is meant as a general purpose language (e.g. to build linux apps on linux). If you want to build iOS and OS X apps, you have to use Xcode on OS X.
